### ISSUE TITLE
[bug] multi-line progressbar shows only one line after printing a warning

### ISSUE THREAD

**Issue by TheStarAlight** [timholy/ProgressMeter.jl#272] opened 2023-07-28 16:57 UTC
Hi, I'm using ProgressMeter for my package, the progress is shown in two lines. When my package throws a warning using `@warn`, the progress would only show the latter line...

Here's an example, while in this example only the former one is shown... very weird...
```
using ProgressMeter
prog1 = ProgressUnknown(dt=0.2, desc="Launching electrons and collecting ...", color = :cyan, spinner = true)
prog2 = Progress(100; dt=0.2, color = :cyan, barlen = 25, barglyphs = BarGlyphs('[', '●', ['◔', '◑', '◕'], '○', ']'), showspeed = true, offset=1)
for i in 1:100
    sleep(0.1)
    if i==1
        @warn "Some warning"
    end
    next!(prog1);next!(prog2)
end
```
Using Julia 1.8.5 and ProgressMeter 1.7.2
Paste it in the REPL and run it once, the first time both lines are shown, while if you run the loop again, the latter line disappears...😂

Thank you for your attention! This package is really useful to me, I'll be grateful if you can help!😋

**Comment by MarcMush** [comment] 2024-01-29 20:35
when I try to reproduce your example, both progressmeters are always printed but the next `print` will overwrite the second one (in the repl, the next `julia>`)
this is because `prog1` is a `ProgressUnknown` so it doesn't know it's finished
this will be fixed if you add `finish!(prog1)`

I didn't see any problem with `@warn`, the behavior is the same for me when commenting in out

**Comment by TheStarAlight** [comment] 2024-01-30 05:13
@MarcMush Thank you for help 🥳! It has been five months and the details are already vague to me. I just tested in my julia 1.9 and everything is fine. Thank you very much!

Btw, I noticed that the introduction of the `offset` param is missing in the readme, and I think that adding a section which describes how to display multiple progressbars might be helpful :D

**Closed** 2024-01-30 09:09 UTC
